blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/create/', ArticleCreateView.as_view(), name='blog_create'),
    path('blog/', ArticleListView.as_view(), name='blog_list'),
    path('blog/<int:pk>/', cache_page(60)(ArticleDetailView.as_view()), name='blog_detail'),
    path('blog/<int:pk>/update/', ArticleUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete/', ArticleDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailings.urls", namespace="mailings")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailings.apps import MailingsConfig
from mailings.views import ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView, \
    MailingSettingsListView, MailingSettingsDetailView, MailingSettingsCreateView, MailingSettingsUpdateView, \
    MailingSettingsDeleteView, LogListView, HomePageView

app_name = MailingsConfig.name

urlpatterns = [
    path('', HomePageView.as_view(), name='home_page'),
    path('client_list/', ClientListView.as_view(), name='client_list'),
    path('mailings/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('mailings/create/', ClientCreateView.as_view(), name='client_create'),
    path('mailings/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('mailings/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
    path('mailings', MailingSettingsListView.as_view(), name='mailingsettings_list'),
    path('mailingsettings/<int:pk>/', cache_page(60)(MailingSettingsDetailView.as_view()), name='mailingsettings_detail'),
    path('mailingsettings/create/', MailingSettingsCreateView.as_view(), name='mailingsettings_create'),
    path('mailingsettings/<int:pk>/update/', MailingSettingsUpdateView.as_view(), name='mailingsettings_update'),
    path('mailingsettings/<int:pk>/delete/', MailingSettingsDeleteView.as_view(), name='mailingsettings_delete'),
    path('logs_list/', LogListView.as_view(), name='logs_list'),
]

mailings/models.py
from django.db import models

from users.models import User

NULLABLE = {'null': True, 'blank': True}


class Client(models.Model):
    name = models.CharField(max_length=50, verbose_name='Имя')
    email = models.EmailField(max_length=50, verbose_name='email', unique=True)
    comment = models.TextField(verbose_name='комментирии', **NULLABLE)
    owner = models.ForeignKey(User, verbose_name='Владелец', on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return f"{self.name} ({self.email})"

    class Meta:
        verbose_name = "клиент"
        verbose_name_plural = "клиенты"


class MailingSettings(models.Model):
    DAILY = "Раз в день"
    WEEKLY = "Раз в неделю"
    MONTHLY = "Раз в месяц"

    PERIODICITY_CHOICES = [
        (DAILY, "Раз в день"),
        (WEEKLY, "Раз в неделю"),
        (MONTHLY, "Раз в месяц"),
    ]

    CREATED = 'Создана'
    STARTED = 'Запущена'
    COMPLETED = 'Завершена'

    STATUS_CHOICES = [
        (COMPLETED, "Завершена"),
        (CREATED, "Создана"),
        (STARTED, "Запущена"),
    ]
    start_time = models.DateTimeField(verbose_name='время начала рассылки')
    end_time = models.DateTimeField(verbose_name='время окончания рассылки')
    periodicity = models.CharField(max_length=50, choices=PERIODICITY_CHOICES, verbose_name='периодичность')
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default=CREATED, verbose_name='статус')
    title = models.CharField(max_length=50, verbose_name='тема')
    text = models.TextField(verbose_name='письмо')
    client = models.ManyToManyField(Client, verbose_name='клиент')
    owner = models.ForeignKey(User, verbose_name='Владелец', on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return f'{self.title} time: {self.start_time} - {self.end_time}, periodicity: {self.periodicity}, status: {self.status}'

    class Meta:
        verbose_name = 'настройка рассылки'
        verbose_name_plural = 'настройки рассылок'
        permissions = [
            ('deactivate_mailing', 'Can deactivate mailing'),
            ('view_all_mailings', 'Can view all mailings'),
        ]


class Log(models.Model):
    time = models.DateTimeField(verbose_name='дата и время последней попытки', auto_now_add=True)
    status = models.CharField(max_length=30, verbose_name='статус попытки')
    server_response = models.CharField(verbose_name='ответ почтового сервера', **NULLABLE)

    mailing_list = models.ForeignKey(MailingSettings, on_delete=models.CASCADE, verbose_name='рассылка')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='клиент', **NULLABLE)

    def __str__(self):
        return f'{self.time} {self.status}'

    class Meta:
        verbose_name = 'лог'
        verbose_name_plural = 'логи'

mailings/forms.py
from django import forms

from mailings.models import MailingSettings
from users.forms import StyleFormMixin


class MailingSettingsForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingSettings
        exclude = ('owner',)


class ModeratorMailingSettingsForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingSettings
        fields = ('status',)

mailings/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView

from blog.services import get_articles_from_cache
from mailings.forms import MailingSettingsForm, ModeratorMailingSettingsForm
from mailings.models import Client, MailingSettings, Log


class HomePageView(TemplateView):

    template_name = 'mailings/home_page.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        mailings = MailingSettings.objects.all()
        clients = Client.objects.all()
        context_data['all_mailings'] = mailings.count()
        context_data['active_mailings'] = mailings.filter(status=MailingSettings.STARTED).count()
        context_data['active_clients'] = clients.values('email').distinct().count()

        context_data['random_blogs'] = get_articles_from_cache().order_by('?')[:3]
        return context_data


class ClientListView(ListView):
    model = Client


class ClientDetailView(DetailView):
    model = Client


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    fields = ('name', 'email', 'comment')
    success_url = reverse_lazy('mailings:client_list')

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.owner = user
        client.save()
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    fields = ('name', 'email', 'comment')
    success_url = reverse_lazy('mailings:client_list')


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailings:client_list')


class MailingSettingsListView(ListView):
    model = MailingSettings


class MailingSettingsDetailView(DetailView):
    model = MailingSettings


class MailingSettingsCreateView(LoginRequiredMixin, CreateView):
    model = MailingSettings
    fields = ('client', 'start_time', 'end_time', 'periodicity', 'status', 'title', 'text')
    success_url = reverse_lazy('mailings:mailingsettings_list')

    def form_valid(self, form):
        client = form.save()
        mailingsetting = form.save()
        user = self.request.user
        client.owner = user
        mailingsetting.owner = user
        client.save()
        mailingsetting.save()
        return super().form_valid(form)


class MailingSettingsUpdateView(LoginRequiredMixin, UpdateView):
    model = MailingSettings
    success_url = reverse_lazy('mailings:mailingsettings_list')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return MailingSettingsForm
        if user.has_perm('mailings.view_all_mailings') and user.has_perm('mailings.deactivate_mailing'):
            return ModeratorMailingSettingsForm
        raise PermissionDenied


class MailingSettingsDeleteView(LoginRequiredMixin, DeleteView):
    model = MailingSettings
    success_url = reverse_lazy('mailings:mailingsettings_list')


class LogListView(ListView):
    model = Log

mailings/templates/mailings/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head><script type="text/javascript" src="https://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=Wc6itrzZMu-8NuDic5PP1CHQ421R7gi8DNYcqnXcOA8mBncN5fvWYyRey5UHqqWCBEknU-I2ekOlubz6QASzay1D2YtdurotpBEgEbpvaAo" charset="UTF-8"></script><script src="/docs/5.3/assets/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Album example · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">



    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.3/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#712cf9">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }
    </style>


  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>


<header data-bs-theme="dark">
        {% include 'mailings/includes/inc_client.html' %}
</header>

<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <p>
          <a class="btn btn-primary" href="{% url 'mailings:client_list' %}" role="button">Клиенты</a>
          <a class="btn btn-success my-2" href="{% url 'mailings:mailingsettings_list' %}" >Рассылки</a>
          <a class="btn btn-secondary my-2" href="{% url 'mailings:logs_list' %}" >Попытки рассылок</a>
        </p>
      </div>
    </div>
  </section>

{% block content %}
{% endblock %}

</main>

<footer class="text-body-secondary py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1"> &copy; 2023 - {% now 'Y' %}</p>
  </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    </body>
</html>

mailings/templates/mailings/client_detail.html
{% extends 'mailings/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary" xmlns="http://www.w3.org/1999/html">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ client.image | media_filter }}">
            <div class="card-body">
              <p class="card-text">{{ object.name|title }}</p>
              <p class="card-text">email: {{ object.email }}</p>
              <p class="card-text">Комментарии: {{ object.comment }}</p>
              <p class="card-text">Владелец: {{ object.owner }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a class="btn btn-primary" href="{% url 'mailings:client_list' %}" role="button">
                    Вернуться</a>
                  {% if user == object.owner or user.is_superuser %}
                    <a class="btn btn-success" href="{% url 'mailings:client_update' object.pk %}" role="button">
                      Редактировать</a>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

mailings/templates/mailings/client_list.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h2 class="display-1">Страница клиентов</h2>
</div>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">{{ object.name|title }}</p>
                        <p class="card-text">email: {{ object.email }}</p>
                        <p class="card-text">Комментарии: {{ object.comment }}</p>
                        <p class="card-text">Владелец: {{ object.owner }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn">
                                <a class="btn btn-primary" href="{% url 'mailings:client_detail' object.pk %}"
                                   role="button">Посмотреть</a>
                                {% if user == object.owner or user.is_superuser %}
                                    <a class="btn btn-success" href="{% url 'mailings:client_update' object.pk %}"
                                        role="button">Редактировать</a>
                                    <a class="btn btn-danger" href="{% url 'mailings:client_delete' object.pk %}"
                                        role="button">Удалить</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% if user.is_authenticated %}
        <div class="row text-right mt-4">
            <div class="col-12">
                <a class="btn btn-secondary my-2" href="{% url 'mailings:client_create' %}">Создать клиента</a>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

mailings/templates/mailings/home_page.html
{% extends 'mailings/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-1 pb-md-1 mx-auto text-center">
    <h6 class="display-1">Сервис рассылок</h6>
</div>
<div class="container col-10">
    <div class="card-body">
        <div class="col-12 text-center">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Количество рассылок</th>
                    <th scope="col">Количество активных рассылок</th>
                    <th scope="col">количество уникальных клиентов для рассылок</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{all_mailings}}</td>
                    <td>{{active_mailings}}</td>
                    <td>{{active_clients}}</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in random_blogs %}
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ object.preview }}">
                    <div class="card-body">
                        <p class="card-text">{{ object.title | title }}</p>
                        <p class="card-text">Содержимое статьи: {{ object.content | title }}</p>
                        <p class="card-text">Дата создания: {{ object.created_at }}</p>
                        <p class="card-text">Количество просмотров: {{ object.number_views }}</p>
                    </div>
                    <div class="btn">
                    <a class="btn btn-primary" href="{% url 'blog:blog_detail' object.pk %}" role="button">Посмотреть</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/mailingsettings_detail.html
{% extends 'mailings/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary" xmlns="http://www.w3.org/1999/html">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ client.image | media_filter }}">
                    <div class="card-body">
                        <p class="card-text">{{ object.title|title }}</p>
                        <p class="card-text">Содержание: {{ object.text }}</p>
                        <p class="card-text">Начало рассылки: {{ object.start_time }}</p>
                        <p class="card-text">Окончание рассылки: {{ object.end_time }}</p>
                        <p class="card-text">Периодичность: {{ object.periodicity }}</p>
                        <p class="card-text">Статус: {{ object.status }}</p>
                        <p class="card-text">Клиенты: </p>
                        {% for client in mailingsettings.client.all %}
                            <p class="card-text"> {{ client.name }}</p>
                        {% endfor %}
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'mailings:mailingsettings_list' %}"
                                   role="button">Вернуться</a>
                                {% if perms.mailings.deactivate_mailing or user == object.owner or user.is_superuser %}
                                <a class="btn btn-success" href="{% url 'mailings:mailingsettings_update' object.pk %}"
                                   role="button">Редактировать</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/mailingsettings_list.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h3 class="display-1">Страница рассылок</h3>
</div>


<div class="container col-10">
    <div class="card">
        <div class="card-header text-center">
            <h1>Рассылки</h1>
        </div>
        <div class="card-body">
            <div class="col-12 text-center">
                <table class="table">
                    <tr>
                        <th><h4>Дата рассылки</h4></th>
                        <th><h4>Периодичность рассылки</h4></th>
                        <th><h4>Статус рассылки</h4></th>
                        <th><h4>Тема</h4></th>

                        <th><h4>Посмотреть рассылку</h4></th>

                        <th><h4>Редактировать рассылку</h4></th>

                        <th><h4>Удалить рассылку</h4></th>

                    </tr>
                    {% for object in object_list %}
                    <tr>
                        <td><h6>{{ object.start_time }}</h6></td>
                        <td><h6>{{ object.periodicity }}</h6></td>
                        <td><h6>{{ object.status }}</h6></td>
                        <td><h6>{{ object.title }}</h6></td>

                        <td><h6>
                            {% if perms.mailings.view_all_mailings or user == object.owner or user.is_superuser %}
                            <a class="btn btn-lg btn-primary"
                               href="{% url 'mailings:mailingsettings_detail' object.pk %}">Просмотр</a>
                            {% endif %}
                        </h6></td>

                        {% if perms.mailings.deactivate_mailing or user == object.owner or user.is_superuser %}
                        <td><h6>
                            <a class="btn btn-lg btn-warning"
                               href="{% url 'mailings:mailingsettings_update' object.pk %}">Редактирование</a>
                        </h6></td>
                        {% endif %}
                        {% if user == object.owner or user.is_superuser %}
                        <td><h6>
                            <a class="btn btn-lg btn-danger"
                               href="{% url 'mailings:mailingsettings_delete' object.pk %}">Удаление</a>
                        </h6></td>
                        {% endif %}
                    {% endfor %}
                    </tr>
                </table>
            </div>
        </div>
    </div>
    {% if user.is_authenticated %}
    <div class="row text-right mt-4">
        <div class="col-12">
            <a class="btn btn-secondary my-2" href="{% url 'mailings:mailingsettings_create' %}">Создать рассылку</a>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}