blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/create/', ArticleCreateView.as_view(), name='blog_create'),
    path('blog/', ArticleListView.as_view(), name='blog_list'),
    path('blog/<int:pk>/', cache_page(60)(ArticleDetailView.as_view()), name='blog_detail'),
    path('blog/<int:pk>/update/', ArticleUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete/', ArticleDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailings.urls", namespace="mailings")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {"blank": True, "null": True}


class Article(models.Model):
    title = models.CharField(
        max_length=150, verbose_name="Заголовок", help_text="Введите заголовок статьи"
    )

    content = models.TextField(
        verbose_name="Содержимое статьи", help_text="Введите содержимое статьи"
    )

    preview = models.ImageField(
        upload_to="blog/photo",
        verbose_name="Превью",
        help_text="Загрузите превью статьи",
        **NULLABLE
    )

    number_views = models.PositiveIntegerField(
        verbose_name="Количество просмотров",
        help_text="Укажите количество просмотров",
        default=0,
    )

    created_at = models.DateField(
        auto_now_add=True,
        verbose_name="Дата создания",
        help_text="Укажите дату создания",
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse

from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.models import Article


class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    fields = ('title', 'content', 'preview',)
    success_url = reverse_lazy('blog:blog_list')


class ArticleUpdateView(LoginRequiredMixin, UpdateView):
    model = Article
    fields = ('title', 'content', 'preview',)

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])


class ArticleListView(ListView):
    model = Article


class ArticleDetailView(DetailView):
    model = Article

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.number_views += 1
        self.object.save()
        return self.object


class ArticleDeleteView(LoginRequiredMixin, DeleteView):
    model = Article
    success_url = reverse_lazy('blog:blog_list')

blog/templates/blog/article_confirm_delete.html
{% extends 'mailings/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-2">
                <div class="card">
                    <div class="card-body">
                        <form method='post'>
                            {% csrf_token %}
                            <p>Хотите удалить статью "{{object.title}}"?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">Отменить</a>
                         </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/article_detail.html
{% extends 'mailings/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary" xmlns="http://www.w3.org/1999/html">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ product.image | media_filter }}">
            <div class="card-body">
              <p class="card-text">{{ article.title | title }} </p>
              <p class="card-text">Содержимое статьи:  {{ article.content | title }}</p>
              <p class="card-text">Дата создания: {{ article.created_at }}</p>
              <p class="card-text">Количество просмотров:  {{ article.number_views }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">Вернуться</a>
                  {% if user.is_authenticated %}
                  <a class="btn btn-success" href="{% url 'blog:blog_update' article.pk %}" role="button">Редактировать</a>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

blog/templates/blog/article_form.html
{% extends 'mailings/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method='post'>
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                         </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/article_list.html
{% extends 'mailings/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for article in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ article.preview | media_filter }}">
                    <div class="card-body">
                        <p class="card-text">{{ article.title | title }}</p>
                        <p class="card-text">Содержимое статьи: {{ article.content | title }}</p>
                        <p class="card-text">Дата создания: {{ article.created_at }}</p>
                        <p class="card-text">Количество просмотров: {{ article.number_views }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn">
                                <a class="btn btn-primary" href="{% url 'blog:blog_detail' article.pk %}" role="button">Посмотреть</a>
                                {% if user.is_authenticated %}
                                <a class="btn btn-success" href="{% url 'blog:blog_update' article.pk %}" role="button">Редактировать</a>
                                <a class="btn btn-danger" href="{% url 'blog:blog_delete' article.pk %}" role="button">Удалить</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="row text-right mt-4">
            <div class="col-12">
                {% if user.is_authenticated %}
                <a class="btn btn-secondary my-2" href="{% url 'blog:blog_create' %}">Создать блог</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}