blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/create/', ArticleCreateView.as_view(), name='blog_create'),
    path('blog/', ArticleListView.as_view(), name='blog_list'),
    path('blog/<int:pk>/', cache_page(60)(ArticleDetailView.as_view()), name='blog_detail'),
    path('blog/<int:pk>/update/', ArticleUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete/', ArticleDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailings.urls", namespace="mailings")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, ProfileView, UserListView, toggle_activity

app_name = UsersConfig.name

urlpatterns = [
    path('users_list/', UserListView.as_view(), name='users_list'),
    path('toggle_activity/<int:pk>/', toggle_activity, name='toggle_activity'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('profile/', ProfileView.as_view(), name='profile')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Email')
    avatar = models.ImageField(upload_to='users/avatars/', **NULLABLE)
    phone = models.CharField(max_length=40, verbose_name='Телефон', **NULLABLE)
    country = models.CharField(max_length=40, verbose_name='Страна', **NULLABLE)
    token = models.CharField(max_length=100, verbose_name='Токен', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        permissions = [
            ('deactivate_user', 'Can deactivate user'),
            ('view_all_users', 'Can view all users'),
        ]


    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

#from catalog.forms import StyleFormMixin
from users.models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            if not isinstance(field.widget, forms.CheckboxInput):
                field.widget.attrs['class'] = 'form-control'


class UserRegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'avatar', 'phone', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import secrets

from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView

from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm, UserProfileForm
from users.models import User


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_activ = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}/'
        send_mail(
            subject='Подтверждение почты',
            message=f'Здравствуйте. Перейдите по ссылки для подтверждения почты {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserListView(PermissionRequiredMixin, ListView):
    model = User
    permission_required = 'users.view_all_users'


@permission_required('users.deactivate_user')
def toggle_activity(request, pk):
    user = User.objects.get(pk=pk)
    if user.is_active:
        user.is_active = False
    else:
        user.is_active = True
    user.save()
    return redirect(reverse('users:users_list'))

users/templates/users/login.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Вход
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        Войти
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">

                <div class="card-header">
                    {% if object %}
                    <h5 class="card-title">
                        Редактирование профиля
                    </h5>
                    {% else %}
                    <h3 class="card-title">
                        Регистрация
                    </h3>
                    {% endif %}
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        Зарегистрироваться
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'mailings/base.html' %}
{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h4 class="jumbotron-heading">Список пользователей</h4>
    </div>
</section>
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">Email</th>
        <th scope="col">Телефон</th>
        <th scope="col">Статус активности</th>
        <th scope="col">Статус персонала</th>
        <th scope="col">Изменение статуса</th>
    </tr>
    </thead>
    <tbody>
    {% for user in object_list %}
    <tr>
        <td>{{ user.email }}</td>
        <td>{{ user.phone }}</td>
        <td>{{ user.is_active }}</td>
        <td>{{ user.is_staff }}</td>
        <td>{% if perms.users.deactivate_user %}
            {% if user.is_active %}
            <a href="{% url 'users:toggle_activity' user.pk %}"
               class="btn btn-sm btn-outline-danger">Деактивировать</a>
            {% else %}
            <a href="{% url 'users:toggle_activity' user.pk %}"
               class="btn btn-sm btn-outline-success">Активировать</a>
            {% endif %}
            {% endif %}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}